<Workspace Version="0.8.2.2392" X="1253.5483493247" Y="-285.610351600957" zoom="0.64874624376471" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSFunction guid="cfd4dda4-31a0-4fbc-abe6-b065c28ff3e2" type="Dynamo.Nodes.DSFunction" nickname="Geometry.Explode" x="142.099781613745" y="60.0856744965696" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Explode" />
    <Dynamo.Nodes.DSFunction guid="b175dc4e-4bd1-4969-82dc-a87f0ce60a07" type="Dynamo.Nodes.DSFunction" nickname="MeshTools.Tessellate" x="523.771710647939" y="115.551100796151" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="MeshTools\bin\Debug\MeshTools.dll" function="MeshTools.MeshTools.Tessellate@Autodesk.DesignScript.Geometry.Surface[],double,int" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="d6bb8c30-5722-4a06-9345-f6f3edb2ce4f" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="383.608921660513" y="145.951100796151" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="0.001;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="67bc0b7a-d173-4f1d-a870-b173ec8f567d" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="390.808921660514" y="228.351100796151" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="10;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="7c1d3e37-8e2e-4173-8e7c-2f6d41cbc187" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1086.59359134729" y="-32.0425452984232" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="list[0];&#xA;list[1];&#xA;list[2];" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="3aceb43e-2fdb-4a99-8fd2-ba59ae7f740e" type="Dynamo.Nodes.DSFunction" nickname="Facet3d.ByPoints" x="1564.1203853175" y="68.5326410335754" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Facet3d.ByPoints@var,var,var" />
    <Dynamo.Nodes.DSFunction guid="9c2eca6c-5ab7-4d16-a6f3-27271bae103b" type="Dynamo.Nodes.DSFunction" nickname="STL.ByFacets" x="1706.06122429975" y="68.5326410335754" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.STL.ByFacets@var[]" />
    <Dynamo.Nodes.DSFunction guid="957ee957-02eb-437e-94bb-ad1f1b8ec4dc" type="Dynamo.Nodes.DSFunction" nickname="Point3d.ByCoordinates" x="1336.46341888524" y="-42.1662872076158" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Point3d.ByCoordinates@double,double,double" />
    <Dynamo.Nodes.DSFunction guid="6b1a63a0-ce1e-4a7d-9aa5-17475b23f013" type="Dynamo.Nodes.DSFunction" nickname="Point3d.ByCoordinates" x="1337.26341888524" y="96.3831769129797" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Point3d.ByCoordinates@double,double,double" />
    <Dynamo.Nodes.DSFunction guid="908eab93-7b0b-4fb4-a266-1ef6361fab86" type="Dynamo.Nodes.DSFunction" nickname="Point3d.ByCoordinates" x="1338.78741802574" y="232.849406654622" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Point3d.ByCoordinates@double,double,double" />
    <Dynamo.Nodes.DSFunction guid="273371d7-c8f0-4c99-a493-aeb02525a261" type="Dynamo.Nodes.DSFunction" nickname="Point.X" x="936.925190687182" y="-29.5404799195721" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.X" />
    <Dynamo.Nodes.DSFunction guid="0ed1a482-e7d3-4416-af78-57baa533c095" type="Dynamo.Nodes.DSFunction" nickname="Point.Y" x="935.474654807777" y="114.062572141447" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Y" />
    <Dynamo.Nodes.DSFunction guid="1f3acc4c-0721-407c-a0c3-874b6c60e172" type="Dynamo.Nodes.DSFunction" nickname="Point.Z" x="935.474654807777" y="253.314016564252" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Z" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="6a08f236-352e-4551-8949-99ed3c2653d0" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1086.59359134729" y="111.646041487619" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="list[0];&#xA;list[1];&#xA;list[2];" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="22e5933c-134c-4f0d-9c91-55bf2b2af594" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1086.59359134729" y="255.095342392808" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="list[0];&#xA;list[1];&#xA;list[2];" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="98753061-6787-4b1e-8374-219b94411d65" type="Dynamo.Nodes.DSFunction" nickname="STLxGrids.ByHeightAndGrid2d" x="2730.16123005636" y="319.09028468152" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.STLxGrids.ByHeightAndGrid2d@double[],var[]" />
    <Dynamo.Nodes.DSFunction guid="3f2bf4c8-a5e8-47e8-88df-98b2b3edd409" type="Dynamo.Nodes.DSFunction" nickname="Shell.BySTL" x="2000.74992328865" y="66.7644292036161" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Shell.BySTL@var" />
    <Dynamo.Nodes.DSFunction guid="73f75a9c-506b-4224-8754-b253c5a69949" type="Dynamo.Nodes.DSFunction" nickname="STLxOutlines.ByHeightAndOutline2d" x="2429.85839469472" y="1.81397809872396" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.STLxOutlines.ByHeightAndOutline2d@double[],var[]" />
    <Dynamo.Nodes.DSFunction guid="00ed6579-98e8-4588-9b15-3af8fa2918af" type="Dynamo.Nodes.DSFunction" nickname="Grid2d.ByOutline" x="2549.36454650758" y="228.983503620032" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Grid2d.ByOutline@var,var" />
    <Dynamo.Nodes.Watch guid="e8c1bf73-ef92-4794-baf2-54166212aa11" type="Dynamo.Nodes.Watch" nickname="adjusted total shell height" x="-921.656614397733" y="1112.86615921126" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" />
    <DSIronPythonNode.PythonNode guid="df46f727-4615-4667-8cd9-9bb20f279df3" type="DSIronPythonNode.PythonNode" nickname="getSolidDifference" x="-21.1957363326352" y="59.2243956956584" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

solidList = IN[0]

if len(solidList)&gt;1:
	outerSolid = solidList[0]
	for i in range(1, len(solidList)):
		result = Solid.Difference(outerSolid, solidList[i])
		outerSolid = result
		OUT = [outerSolid]
else:
	OUT = solidList


</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="f8ab262a-a35c-4f2b-a256-9a075204c27d" type="Dynamo.Nodes.DSFunction" nickname="Curve.ExtrudeAsSolid" x="-490.669503619684" y="671.951308721531" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.ExtrudeAsSolid@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <DSIronPythonNode.PythonNode guid="262fa68e-be48-4781-a300-fbfa182e49c9" type="DSIronPythonNode.PythonNode" nickname="Floor Maker" x="-1409.37013086819" y="1723.75896582336" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")
import random
#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

recList=IN[0]
floorHeights = IN[1]


#makes floors translate to given height list---------------------------------------------------------------------------------------
def floorTranslator(recList,flrHtList):
	outlines = []
	#define the translation vector
	ptA = Point.ByCoordinates(0,0,0)
	ptB = Point.ByCoordinates(0,0,100)
	vec = Vector.ByTwoPoints(ptA,ptB)
	
	for j in range(len(flrHtList)):
		dist = flrHtList[j]
		tempList = []
		
		for i in range(len(recList)):
			rec = recList[i]
			newRec = rec.Translate(vec,dist)
			tempList.append(newRec)
		outlines.append(tempList)
	return outlines
#---------------------------------------------------------------------------------------------------------------------------------


out = floorTranslator(recList,floorHeights)

#Assign your output to the OUT variable
OUT = out</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="8d156ad0-9879-4cd4-bae3-11cffb0e0d43" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-1393.30025697273" y="1871.77003888807" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="list[0];&#xA;list[1];" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="91f194fd-4ac2-41ec-bd1b-3cc4f4e1949a" type="DSIronPythonNode.PythonNode" nickname="Generates Floor Plane Heights" x="-1627.98668204807" y="1858.64421317171" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="5">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
import math
#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

#inputs------------------------------------------------------------
twr_Height = IN[0]
regflr_Ht  = IN[1]
mechflr_Ht = IN[2]
keyflr_Mech= IN[3]
hasMechFloor = IN[4]
#inputs------------------------------------------------------------

approxNum_Floors  =  twr_Height / regflr_Ht
numberof_MechFloors = math.ceil(approxNum_Floors / keyflr_Mech)
height_Counter = 0
height_List=[]
height = 0
tag = 0

while height&lt;twr_Height:		
	#iterate to add the heights for the regular floors till first mechanical lvl
	for i in range(keyflr_Mech):
		if i == 0 and tag == 0:
			height += 0
			tag = 1
		else:
			height += regflr_Ht
		height_List.append(height)
		
		if (hasMechFloor and (height + mechflr_Ht + 1) &gt; twr_Height): break
		if (not hasMechFloor) and height &gt; twr_Height: break			
				
	if ((height) &gt; twr_Height):	break	

	if hasMechFloor:	
		height += mechflr_Ht
		# add the mechanical floor height to the height list
		height_List.append(height)
 
new_shell_height = height

#Assign your output to the OUT variable
OUT = height_List, new_shell_height</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="f2788187-ebcc-4a16-8795-1e3c3329af14" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="split output" x="-1058.9164895923" y="374.841890190328" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="list[0];&#xA;list[1];" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="3cbc7df0-5e9a-48b2-9a84-10f7ff5f756b" type="DSIronPythonNode.PythonNode" nickname="Irregular Shape Maker" x="-1262.97962057957" y="427.224426992606" isVisible="false" isUpstreamVisible="false" lacing="Disabled" isSelectedInput="False" inputcount="5">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN


x = IN[0]
y = IN[1]
lenX = IN[2]
lenY = IN[3]
type = int(IN[4])

pt = Point.ByCoordinates(x,y,0)

#find the closest point from a point-------------------------------------------------------------------------------------	
def closestPoint(ptA,ptList):
	shortLen	=	100000000000000 # set as a really high value
	index		=	0
	for i in range(len(ptList)):
		vec				= 	Vector.ByTwoPoints(ptA,ptList[i])
		vecLen			=	vec.Length
		if ( vecLen &lt; shortLen ):
			shortLen	=	vecLen
			index		=	i
	# returns the closest point to ptA from the list
	return ptList[index]
#------------------------------------------------------------------------------------------------------------------------




def typeListMaker():
	if type == 1:		
		len = [lenX,lenY,lenX,lenY]
		dir = [0,0,1,1]
		sides = 4		
	if type == 2:
		a = int(lenX/2)		
		b = int(lenY/3)			
		len = [lenX,a,b,lenY-a,lenX-b,lenY]
		dir = [0,0,1,0,1,1]
		sides = 6
	if type == 3:		
		a1 = int(lenX/3)
		a2 = int(lenX/4)
		b = int(lenY/2)	
		len = [lenX,lenY,a1,b,a2,b,lenX-a1-a2,lenY]
		dir = [0,0,1,1,1,0,1,1]
		sides = 8
	if type == 4:
		len = [lenX,lenY,lenX,lenY]
		dir = [0,0,1,1]
		sides = 4	
	return len,dir,sides


#function which makes l shaped profile-----------------------------------------------------------------------------------
def shapeGenerator():
	linList = []
	ptList = []
	
	ptX = Point.ByCoordinates(200000,0,0)
	ptY = Point.ByCoordinates(0,200000,0)
	
	xvec = Vector.ByTwoPoints(pt,ptX)
	yvec = Vector.ByTwoPoints(pt,ptY)
	xvecN = xvec.Reverse()
	yvecN = yvec.Reverse()
	a = int(lenX/2)
	b = int(lenY/3)
	 
	len = typeListMaker()[0]
	dir = typeListMaker()[1]
	sides = typeListMaker()[2]
	
	point = pt
	ptList.append(point)
	for i in range(sides):
		#toggle vec values
		if i%2 ==0:
			if dir[i]==0: vec = xvec
			else: vec = xvecN
		else:
			if dir[i]==0: vec = yvec
			else: vec = yvecN	
		l1 = Line.ByStartPointDirectionLength(point,vec,len[i])
		linList.append(l1)
		point = l1.EndPoint
		ptList.append(point)
	polygon = Polygon.ByPoints(ptList)
	polyCenter = polygon.Center()
	closePt = closestPoint(polyCenter,ptList)
	return [polygon],closePt
#---------------------------------------------------------------------------------------------------------------------------



#function which makes  shaped profile---------------------------------------------------------------------------------------
def shapeGenType4():
	linList = []
	ptList = []
	
	ptX = Point.ByCoordinates(200000,0,0)
	ptY = Point.ByCoordinates(0,200000,0)
	
	xvec = Vector.ByTwoPoints(pt,ptX)
	yvec = Vector.ByTwoPoints(pt,ptY)
	xvecN = xvec.Reverse()
	yvecN = yvec.Reverse()
		
	 
	len = typeListMaker()[0]
	dir = typeListMaker()[1]
	sides = typeListMaker()[2]
	
	#1st outer polygon===============================================================
	point = pt
	ptList.append(point)
	for i in range(sides):
		#toggle vec values
		if i%2 ==0:
			if dir[i]==0: vec = xvec
			else: vec = xvecN
		else:
			if dir[i]==0: vec = yvec
			else: vec = yvecN	
		l1 = Line.ByStartPointDirectionLength(point,vec,len[i])
		linList.append(l1)
		point = l1.EndPoint
		ptList.append(point)
	polygon = Polygon.ByPoints(ptList)
	polyCenter = polygon.Center()
	closePt = closestPoint(polyCenter,ptList)
	#================================================================================
	a = lenX/1.8
	b = lenY/2.2
	len[0] = len[0] - a
	len[1] = len[1] - b
	len[2] = len[0]
	len[3] = len[1]
	
	linList = []
	ptList = []
	#inner polygon====================================================================
	point = pt
	ptList.append(point)
	for i in range(sides):
		#toggle vec values
		if i%2 ==0:
			if dir[i]==0: vec = xvec
			else: vec = xvecN
		else:
			if dir[i]==0: vec = yvec
			else: vec = yvecN	
		l1 = Line.ByStartPointDirectionLength(point,vec,len[i])
		linList.append(l1)
		point = l1.EndPoint
		ptList.append(point)
	polygon2 = Polygon.ByPoints(ptList)
	ptN = Point.ByCoordinates(pt.X+(a/2),pt.Y+(b/2))
	vecShift = Vector.ByTwoPoints(pt,ptN)
	polygon2 = polygon2.Translate(vecShift)
	#================================================================================
	
	
	return [polygon,polygon2],closePt
#---------------------------------------------------------------------------------------------------------------------------


if type == 4: out = shapeGenType4()
else : out = shapeGenerator()

#Assign your output to the OUT variable
OUT = out</Script>
    </DSIronPythonNode.PythonNode>
    <DSCoreNodesUI.Input.IntegerSlider guid="33ba284a-d44c-483c-8356-6b522a1aba3b" type="DSCoreNodesUI.Input.IntegerSlider" nickname="Shell Type" x="-1702.79224385071" y="590.769161262728" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Int32>1</System.Int32>
      <Range min="1" max="4" step="1" />
    </DSCoreNodesUI.Input.IntegerSlider>
    <DSCoreNodesUI.Input.IntegerSlider guid="788b2098-6426-4a91-9730-6c07b25b29e9" type="DSCoreNodesUI.Input.IntegerSlider" nickname="akaba.input.requirements.site.width" x="-1701.82572353805" y="703.415971828346" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Int32>30</System.Int32>
      <Range min="0" max="200" step="1" />
    </DSCoreNodesUI.Input.IntegerSlider>
    <DSCoreNodesUI.Input.DoubleSlider guid="8b41da6c-373c-4485-9c96-f8e51cbd3c3f" type="DSCoreNodesUI.Input.DoubleSlider" nickname="akaba.input.requirements.totalUsableArea" x="-1704.47146895043" y="848.9786712295" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Double>32312.2</System.Double>
      <Range min="0" max="100000" step="0.1" />
    </DSCoreNodesUI.Input.DoubleSlider>
    <DSCoreNodesUI.Input.IntegerSlider guid="4839d30b-44d9-4ac2-8782-ae7852b2d848" type="DSCoreNodesUI.Input.IntegerSlider" nickname="akaba.input.requirements.site.height" x="-1703.05103594057" y="765.211098702104" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Int32>30</System.Int32>
      <Range min="10" max="200" step="1" />
    </DSCoreNodesUI.Input.IntegerSlider>
    <DSCoreNodesUI.Input.IntegerSlider guid="3583cc96-63cb-47e9-8334-6a5a81c8d474" type="DSCoreNodesUI.Input.IntegerSlider" nickname="pos Y" x="-1705.24226564225" y="370.313253609642" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Int32>0</System.Int32>
      <Range min="0" max="200" step="1" />
    </DSCoreNodesUI.Input.IntegerSlider>
    <DSCoreNodesUI.Input.IntegerSlider guid="e762aceb-495d-4afd-b038-88c38e57ac1e" type="DSCoreNodesUI.Input.IntegerSlider" nickname="pos X" x="-1705.07415570322" y="313.319062169192" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Int32>0</System.Int32>
      <Range min="-200" max="0" step="1" />
    </DSCoreNodesUI.Input.IntegerSlider>
    <Dynamo.Nodes.CodeBlockNodeModel guid="da155264-2076-41e9-bec4-af95dcceadae" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="User Input Floor Heights" x="-1650.72150586269" y="928.396373940841" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="regularFloorHeight = 3.5;&#xA;mechanicalFloorHeight = 7;&#xA;mechFloorFrequency = 18;&#xA;hasMechFloor = false;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="3becfda5-9309-446f-9c2d-977f26d6a0a1" type="Dynamo.Nodes.DSFunction" nickname="Shell.GetFloorOutline" x="2253.12337889323" y="67.4480621646217" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Shell.GetFloorOutline@double" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="62820211-99d7-492f-b4c8-94fb30778f3e" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="height list" x="2013.60652022522" y="318.682162620706" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="list;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="d9387d71-ab8e-45e1-9e1c-13503f78d2fa" type="Dynamo.Nodes.DSFunction" nickname="GridBasis.BySize" x="2345.46798139701" y="228.983503620032" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.GridBasis.BySize@double,double" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="6317b1a3-ff61-4820-bea8-6e06fc3851eb" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2254.84814799337" y="228.983503620032" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="0.5;&#xA;3.5;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="efda527c-0e38-4458-824c-5be24afed77f" type="Dynamo.Nodes.DSFunction" nickname="STLxOutlines.ToASCII" x="2683.5751547716" y="26.2307812892033" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.STLxOutlines.ToASCII" />
    <Dynamo.Nodes.DSFunction guid="e811a796-6e5b-475b-91ee-58e860f7a9d9" type="Dynamo.Nodes.DSFunction" nickname="STLxGrids.ToASCII" x="2942.60081645548" y="317.187051046316" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.STLxGrids.ToASCII" />
    <Dynamo.Nodes.DSVarArgFunction guid="d7070713-9c39-4b1d-bc11-00ad7eac31eb" type="Dynamo.Nodes.DSVarArgFunction" nickname="String.Concat" x="3097.0544161069" y="-133.000124288384" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.String.Concat@string[]" inputcount="3" />
    <Dynamo.Nodes.DSFunction guid="bf84697c-4f18-4a9a-90b4-a0721483a1a1" type="Dynamo.Nodes.DSFunction" nickname="STL.ToASCII" x="2253.28059831862" y="-134.627234400419" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.STL.ToASCII" />
    <Dynamo.Nodes.DSFunction guid="9328035f-8cc3-4cab-8818-339433070430" type="Dynamo.Nodes.DSFunction" nickname="Mesh.ByInlineData" x="3271.95058792318" y="-159.365786297893" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Mesh.ByInlineData@string,string,var" />
    <Dynamo.Nodes.DSFunction guid="22abe38f-688a-4439-84dd-6b6b50f27647" type="Dynamo.Nodes.DSFunction" nickname="Point3d.Origin" x="3122.13392369813" y="2.08921434339686" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Point3d.Origin" />
    <Dynamo.Nodes.DSFunction guid="1510dc9f-e608-406a-8a55-b3127bcc3f1e" type="Dynamo.Nodes.DSFunction" nickname="Flatten" x="360.408921660514" y="60.2246653676823" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <Dynamo.Nodes.DSFunction guid="2bf8e248-8803-4030-8cc1-ac6ef2951e61" type="Dynamo.Nodes.DSFunction" nickname="List.Transpose" x="738.003815909586" y="115.071135475195" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.Transpose@var[]..[]" />
    <Dynamo.Nodes.DSFunction guid="79136c5b-0a99-435c-ac4e-f04d855a7987" type="Dynamo.Nodes.DSFunction" nickname="akaba.result" x="3606.27109438412" y="-184.241442170879" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Design.AddMesh@var" />
    <Dynamo.Nodes.DSFunction guid="1b394512-c523-4af3-b703-92a6fbfc0457" type="Dynamo.Nodes.DSFunction" nickname="Design.Empty" x="3492.38006128407" y="-216.679433033696" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly=".\ShellTools.dll" function="stuffer.Design.Empty" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="8f34147b-e347-4de4-b8a8-c7c6a503c8b5" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="shell type" x="3012.63504138166" y="-220.121882703415" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="shellType+&quot;&quot;;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="8abccf5a-527f-456d-81f5-f9a510bcd452" type="Dynamo.Nodes.DSFunction" nickname="MeshTools.GetShellHeight" x="-1248.46433068728" y="796.460499684332" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="MeshTools\bin\Debug\MeshTools.dll" function="MeshTools.MeshTools.GetShellHeight@double,double,double,double" />
    <Dynamo.Nodes.DSFunction guid="e0e7b28d-4f08-4591-9d9f-0fc7b32f6f09" type="Dynamo.Nodes.DSFunction" nickname="MeshTools.GetFloorHeights" x="-990.197276210732" y="924.772997219508" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="MeshTools\bin\Debug\MeshTools.dll" function="MeshTools.MeshTools.GetFloorHeights@double,double,double,int,bool" />
    <Dynamo.Nodes.DSFunction guid="32349991-1a1b-4864-99ff-804d2b296b23" type="Dynamo.Nodes.DSFunction" nickname="Geometry.Translate" x="-362.671715917868" y="1041.40810371631" isVisible="false" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector,double" />
    <Dynamo.Nodes.DSFunction guid="f8508df9-53bf-47a3-b72e-fd51f861f1a2" type="Dynamo.Nodes.DSFunction" nickname="Vector.ZAxis" x="-470.266179412833" y="1095.20533546379" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ZAxis" />
    <DSIronPythonNode.PythonNode guid="3e93fda6-8b51-4629-801c-0627e2e5a99e" type="DSIronPythonNode.PythonNode" nickname="Box Maker" x="-1561.05059744777" y="1721.12176664701" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

polygon = IN[0][0]
closPt = IN[0][1]
type = IN[1]
if type!=4:
	polyPts = polygon.Points

#finds the opposite point to the closest point-------------------------------------------------
def oppPointFinder(poly,closPt):
	polyPts = poly.Points
	for i in range(len(polyPts)):
		if closPt == polyPts[i]:
			oppPt = polyPts[i-3]
			index = i
			break	
	return oppPt,index
#---------------------------------------------------------------------------------------------


#find the closest point from a point-------------------------------------------------------------------------------------	
def closestPoint(ptA,ptList):
	shortLen	=	100000000000000 # set as a really high value
	index		=	0
	for i in range(len(ptList)):
		vec				= 	Vector.ByTwoPoints(ptA,ptList[i])
		vecLen			=	vec.Length
		if ( vecLen &lt; shortLen ):
			shortLen	=	vecLen
			index		=	i
	# returns the closest point to ptA from the list
	return ptList[index]
#------------------------------------------------------------------------------------------------------------------------




#func to split the type3 polygon to regular rect and l shape rect-----------------------------
def multiRecMaker():
	oppPt = oppPointFinder(polygon,closPt)[0]
	id = oppPointFinder(polygon,closPt)[1]-3
	siz = len(polyPts)
	
	lin = Line.ByStartPointEndPoint(closPt,polyPts[id+4])
	lin = lin.Extend(300,lin.StartPoint)
	
	crvsPoly = polygon.Curves()
	for crvs in crvsPoly:		
		pt = Geometry.Intersect(lin,crvs)
		if pt != None:
			break
	ptListA = [polyPts[0],pt[0],polyPts[id+4],polyPts[id+5]]
	ptListB = [pt[0],polyPts[id-1],polyPts[id],polyPts[id+1],polyPts[id+2],polyPts[id+3]]
	polyA = Polygon.ByPoints(ptListA)	
	polyB = Polygon.ByPoints(ptListB)
	polyNew = recMakers(polyB)
	#return lin,oppPt,polyPts[id],crvsPoly,pt,polyA,polyB
	return polyA,polyNew[0],polyNew[1]
#----------------------------------------------------------------------------------------------	
	
	
def recFromType4():
	poly1 = polygon[0]
	poly2 = polygon[1]
	polyPts1 = poly1.Points
	polyPts2 = poly2.Points
	pt=[]
	
	lin1 = Line.ByStartPointEndPoint(polyPts2[0],polyPts2[1])
	lin1 = lin1.Extend(300,lin1.StartPoint)
	lin1 = lin1.Extend(300,lin1.EndPoint)
	
	lin2 = Line.ByStartPointEndPoint(polyPts2[2],polyPts2[3])
	lin2 = lin2.Extend(300,lin2.StartPoint)
	lin2 = lin2.Extend(300,lin2.EndPoint)
	
	crvsPoly1 = poly1.Curves()
	for crvs in crvsPoly1:
		ptInt = Geometry.Intersect(lin1,crvs)
		if len(ptInt) == 0:	continue
		else: pt.append(ptInt[0])
		
	ptList1 = [pt[0],pt[1],polyPts1[0],polyPts1[1]]
	polyA = Polygon.ByPoints(ptList1)	
	for crvs in crvsPoly1:		
		ptInt = Geometry.Intersect(lin2,crvs)
		if len(ptInt) == 0:	continue
		else: pt.append(ptInt[0])	
		
	ptList2 = [pt[3],pt[2],polyPts1[2],polyPts1[3]]
	polyB = Polygon.ByPoints(ptList2)
	
	ptList3 = [pt[2],pt[0],polyPts2[1],polyPts2[2]]
	polyC = Polygon.ByPoints(ptList3)
	
	ptList4 = [pt[3],pt[1],polyPts2[0],polyPts2[3]]
	polyD = Polygon.ByPoints(ptList4)
	return polyA,polyB,polyC,polyD
	
	
	
	
#func to convert polygon to a rectangle---------------------------------------------------
def polytoRect(poly):
	crvs = poly.Curves()
	polyPts = poly.Points
	polyCen = poly.Center()
	wid = Line.ByStartPointEndPoint(polyPts[0],polyPts[1]).Length
	ht = Line.ByStartPointEndPoint(polyPts[0],polyPts[3]).Length
	
	cs = CoordinateSystem.ByOrigin(polyCen)
	#rec = Rectangle.ByWidthHeight(cs,wid,ht)
	
	ptList=[]
	for i in range(len(crvs)-1):
		pt = crvs[i].StartPoint
		ptList.append(pt)	
	rec = Rectangle.ByCornerPoints(ptList)
	return rec
#-----------------------------------------------------------------------------------------

#makes two polygons for two places in the l shape---------------------------------------------
def recMakers(poly):
	#poly = multiRecMaker()[1]
	polyPts = poly.Points
	polyCen = poly.Center()
	
	closPt = closestPoint(polyCen,polyPts)
	 
	oppPt = oppPointFinder(poly,closPt)[0]
	id = oppPointFinder(poly,closPt)[1]-3
	line1 = Line.ByStartPointEndPoint(polyPts[id],polyPts[id+1])
	line2 = Line.ByStartPointEndPoint(polyPts[id-1],polyPts[id-2])
	dist = line2.Length	
	ptNew = line1.PointAtParameter(dist/line1.Length)
	
	ptListA = [polyPts[id],polyPts[id-1],polyPts[id-2],ptNew]
	ptListB = [ptNew,polyPts[id-3],polyPts[id-4],polyPts[id-5]]
	
	polyA = Polygon.ByPoints(ptListA)
	polyB = Polygon.ByPoints(ptListB)
	
	return polyA,polyB
#---------------------------------------------------------------------------------------------

if type==1: out = [polygon]
if type==2: out = recMakers(polygon)
if type==3: out = multiRecMaker()
if type==4: out = recFromType4()

recListFinal = [polytoRect(out[i]) for i in range(len(out)) ]
#Assign your output to the OUT variable
OUT = recListFinal
#OUT = recMakers()</Script>
    </DSIronPythonNode.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="cfd4dda4-31a0-4fbc-abe6-b065c28ff3e2" start_index="0" end="1510dc9f-e608-406a-8a55-b3127bcc3f1e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b175dc4e-4bd1-4969-82dc-a87f0ce60a07" start_index="0" end="2bf8e248-8803-4030-8cc1-ac6ef2951e61" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d6bb8c30-5722-4a06-9345-f6f3edb2ce4f" start_index="0" end="b175dc4e-4bd1-4969-82dc-a87f0ce60a07" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="67bc0b7a-d173-4f1d-a870-b173ec8f567d" start_index="0" end="b175dc4e-4bd1-4969-82dc-a87f0ce60a07" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="7c1d3e37-8e2e-4173-8e7c-2f6d41cbc187" start_index="0" end="957ee957-02eb-437e-94bb-ad1f1b8ec4dc" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7c1d3e37-8e2e-4173-8e7c-2f6d41cbc187" start_index="1" end="6b1a63a0-ce1e-4a7d-9aa5-17475b23f013" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7c1d3e37-8e2e-4173-8e7c-2f6d41cbc187" start_index="2" end="908eab93-7b0b-4fb4-a266-1ef6361fab86" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3aceb43e-2fdb-4a99-8fd2-ba59ae7f740e" start_index="0" end="9c2eca6c-5ab7-4d16-a6f3-27271bae103b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9c2eca6c-5ab7-4d16-a6f3-27271bae103b" start_index="0" end="3f2bf4c8-a5e8-47e8-88df-98b2b3edd409" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9c2eca6c-5ab7-4d16-a6f3-27271bae103b" start_index="0" end="bf84697c-4f18-4a9a-90b4-a0721483a1a1" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="957ee957-02eb-437e-94bb-ad1f1b8ec4dc" start_index="0" end="3aceb43e-2fdb-4a99-8fd2-ba59ae7f740e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6b1a63a0-ce1e-4a7d-9aa5-17475b23f013" start_index="0" end="3aceb43e-2fdb-4a99-8fd2-ba59ae7f740e" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="908eab93-7b0b-4fb4-a266-1ef6361fab86" start_index="0" end="3aceb43e-2fdb-4a99-8fd2-ba59ae7f740e" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="273371d7-c8f0-4c99-a493-aeb02525a261" start_index="0" end="7c1d3e37-8e2e-4173-8e7c-2f6d41cbc187" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="0ed1a482-e7d3-4416-af78-57baa533c095" start_index="0" end="6a08f236-352e-4551-8949-99ed3c2653d0" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1f3acc4c-0721-407c-a0c3-874b6c60e172" start_index="0" end="22e5933c-134c-4f0d-9c91-55bf2b2af594" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6a08f236-352e-4551-8949-99ed3c2653d0" start_index="0" end="957ee957-02eb-437e-94bb-ad1f1b8ec4dc" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="6a08f236-352e-4551-8949-99ed3c2653d0" start_index="1" end="6b1a63a0-ce1e-4a7d-9aa5-17475b23f013" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="6a08f236-352e-4551-8949-99ed3c2653d0" start_index="2" end="908eab93-7b0b-4fb4-a266-1ef6361fab86" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="22e5933c-134c-4f0d-9c91-55bf2b2af594" start_index="0" end="957ee957-02eb-437e-94bb-ad1f1b8ec4dc" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="22e5933c-134c-4f0d-9c91-55bf2b2af594" start_index="1" end="6b1a63a0-ce1e-4a7d-9aa5-17475b23f013" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="22e5933c-134c-4f0d-9c91-55bf2b2af594" start_index="2" end="908eab93-7b0b-4fb4-a266-1ef6361fab86" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="98753061-6787-4b1e-8374-219b94411d65" start_index="0" end="e811a796-6e5b-475b-91ee-58e860f7a9d9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3f2bf4c8-a5e8-47e8-88df-98b2b3edd409" start_index="0" end="3becfda5-9309-446f-9c2d-977f26d6a0a1" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="73f75a9c-506b-4224-8754-b253c5a69949" start_index="0" end="efda527c-0e38-4458-824c-5be24afed77f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="00ed6579-98e8-4588-9b15-3af8fa2918af" start_index="0" end="98753061-6787-4b1e-8374-219b94411d65" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="df46f727-4615-4667-8cd9-9bb20f279df3" start_index="0" end="cfd4dda4-31a0-4fbc-abe6-b065c28ff3e2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f8ab262a-a35c-4f2b-a256-9a075204c27d" start_index="0" end="df46f727-4615-4667-8cd9-9bb20f279df3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="91f194fd-4ac2-41ec-bd1b-3cc4f4e1949a" start_index="0" end="8d156ad0-9879-4cd4-bae3-11cffb0e0d43" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f2788187-ebcc-4a16-8795-1e3c3329af14" start_index="0" end="f8ab262a-a35c-4f2b-a256-9a075204c27d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f2788187-ebcc-4a16-8795-1e3c3329af14" start_index="0" end="32349991-1a1b-4864-99ff-804d2b296b23" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3cbc7df0-5e9a-48b2-9a84-10f7ff5f756b" start_index="0" end="f2788187-ebcc-4a16-8795-1e3c3329af14" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="33ba284a-d44c-483c-8356-6b522a1aba3b" start_index="0" end="3cbc7df0-5e9a-48b2-9a84-10f7ff5f756b" end_index="4" portType="0" />
    <Dynamo.Models.ConnectorModel start="33ba284a-d44c-483c-8356-6b522a1aba3b" start_index="0" end="8f34147b-e347-4de4-b8a8-c7c6a503c8b5" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="788b2098-6426-4a91-9730-6c07b25b29e9" start_index="0" end="3cbc7df0-5e9a-48b2-9a84-10f7ff5f756b" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="788b2098-6426-4a91-9730-6c07b25b29e9" start_index="0" end="8abccf5a-527f-456d-81f5-f9a510bcd452" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8b41da6c-373c-4485-9c96-f8e51cbd3c3f" start_index="0" end="8abccf5a-527f-456d-81f5-f9a510bcd452" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="4839d30b-44d9-4ac2-8782-ae7852b2d848" start_index="0" end="3cbc7df0-5e9a-48b2-9a84-10f7ff5f756b" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="4839d30b-44d9-4ac2-8782-ae7852b2d848" start_index="0" end="8abccf5a-527f-456d-81f5-f9a510bcd452" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="3583cc96-63cb-47e9-8334-6a5a81c8d474" start_index="0" end="3cbc7df0-5e9a-48b2-9a84-10f7ff5f756b" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="e762aceb-495d-4afd-b038-88c38e57ac1e" start_index="0" end="3cbc7df0-5e9a-48b2-9a84-10f7ff5f756b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="da155264-2076-41e9-bec4-af95dcceadae" start_index="0" end="8abccf5a-527f-456d-81f5-f9a510bcd452" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="da155264-2076-41e9-bec4-af95dcceadae" start_index="0" end="e0e7b28d-4f08-4591-9d9f-0fc7b32f6f09" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="da155264-2076-41e9-bec4-af95dcceadae" start_index="1" end="e0e7b28d-4f08-4591-9d9f-0fc7b32f6f09" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="da155264-2076-41e9-bec4-af95dcceadae" start_index="2" end="e0e7b28d-4f08-4591-9d9f-0fc7b32f6f09" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="da155264-2076-41e9-bec4-af95dcceadae" start_index="3" end="e0e7b28d-4f08-4591-9d9f-0fc7b32f6f09" end_index="4" portType="0" />
    <Dynamo.Models.ConnectorModel start="3becfda5-9309-446f-9c2d-977f26d6a0a1" start_index="0" end="00ed6579-98e8-4588-9b15-3af8fa2918af" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3becfda5-9309-446f-9c2d-977f26d6a0a1" start_index="0" end="73f75a9c-506b-4224-8754-b253c5a69949" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="62820211-99d7-492f-b4c8-94fb30778f3e" start_index="0" end="73f75a9c-506b-4224-8754-b253c5a69949" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="62820211-99d7-492f-b4c8-94fb30778f3e" start_index="0" end="3becfda5-9309-446f-9c2d-977f26d6a0a1" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="62820211-99d7-492f-b4c8-94fb30778f3e" start_index="0" end="98753061-6787-4b1e-8374-219b94411d65" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d9387d71-ab8e-45e1-9e1c-13503f78d2fa" start_index="0" end="00ed6579-98e8-4588-9b15-3af8fa2918af" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="6317b1a3-ff61-4820-bea8-6e06fc3851eb" start_index="0" end="d9387d71-ab8e-45e1-9e1c-13503f78d2fa" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6317b1a3-ff61-4820-bea8-6e06fc3851eb" start_index="1" end="d9387d71-ab8e-45e1-9e1c-13503f78d2fa" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="efda527c-0e38-4458-824c-5be24afed77f" start_index="0" end="d7070713-9c39-4b1d-bc11-00ad7eac31eb" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="e811a796-6e5b-475b-91ee-58e860f7a9d9" start_index="0" end="d7070713-9c39-4b1d-bc11-00ad7eac31eb" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="d7070713-9c39-4b1d-bc11-00ad7eac31eb" start_index="0" end="9328035f-8cc3-4cab-8818-339433070430" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="bf84697c-4f18-4a9a-90b4-a0721483a1a1" start_index="0" end="d7070713-9c39-4b1d-bc11-00ad7eac31eb" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9328035f-8cc3-4cab-8818-339433070430" start_index="0" end="79136c5b-0a99-435c-ac4e-f04d855a7987" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="22abe38f-688a-4439-84dd-6b6b50f27647" start_index="0" end="9328035f-8cc3-4cab-8818-339433070430" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="1510dc9f-e608-406a-8a55-b3127bcc3f1e" start_index="0" end="b175dc4e-4bd1-4969-82dc-a87f0ce60a07" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2bf8e248-8803-4030-8cc1-ac6ef2951e61" start_index="0" end="273371d7-c8f0-4c99-a493-aeb02525a261" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2bf8e248-8803-4030-8cc1-ac6ef2951e61" start_index="0" end="0ed1a482-e7d3-4416-af78-57baa533c095" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2bf8e248-8803-4030-8cc1-ac6ef2951e61" start_index="0" end="1f3acc4c-0721-407c-a0c3-874b6c60e172" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1b394512-c523-4af3-b703-92a6fbfc0457" start_index="0" end="79136c5b-0a99-435c-ac4e-f04d855a7987" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8f34147b-e347-4de4-b8a8-c7c6a503c8b5" start_index="0" end="9328035f-8cc3-4cab-8818-339433070430" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8abccf5a-527f-456d-81f5-f9a510bcd452" start_index="0" end="e0e7b28d-4f08-4591-9d9f-0fc7b32f6f09" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e0e7b28d-4f08-4591-9d9f-0fc7b32f6f09" start_index="0" end="62820211-99d7-492f-b4c8-94fb30778f3e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e0e7b28d-4f08-4591-9d9f-0fc7b32f6f09" start_index="0" end="32349991-1a1b-4864-99ff-804d2b296b23" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="e0e7b28d-4f08-4591-9d9f-0fc7b32f6f09" start_index="1" end="f8ab262a-a35c-4f2b-a256-9a075204c27d" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="e0e7b28d-4f08-4591-9d9f-0fc7b32f6f09" start_index="1" end="e8c1bf73-ef92-4794-baf2-54166212aa11" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f8508df9-53bf-47a3-b72e-fd51f861f1a2" start_index="0" end="32349991-1a1b-4864-99ff-804d2b296b23" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Models.AnnotationModel guid="652c1dd8-5908-4a3f-88f7-8cd28439664d" annotationText="GENERATES THE BASE OUTLINE FOR THE GIVEN SHELL TYPE" left="-1272.97962057957" top="331.241890190328" width="356.06313098727" height="290.982536802278" fontSize="14" InitialTop="374.841890190328" InitialHeight="225" TextblockHeight="33.6" backgrouund="#FFC1D676">
      <Models ModelGuid="3cbc7df0-5e9a-48b2-9a84-10f7ff5f756b" />
      <Models ModelGuid="f2788187-ebcc-4a16-8795-1e3c3329af14" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="51190de1-30e2-4bea-8d2e-47673d1e802e" annotationText="FOOTPRINT DIMENSIONS" left="-1713.05103594057" top="673.415971828346" width="326.82531240252" height="159.595126873758" fontSize="14" InitialTop="703.415971828346" InitialHeight="159.595126873759" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="788b2098-6426-4a91-9730-6c07b25b29e9" />
      <Models ModelGuid="4839d30b-44d9-4ac2-8782-ae7852b2d848" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="9d544414-382c-4027-aace-02aa2d74c4f3" annotationText="1: Rectangular &#xD;&#xA;2: L-Shape&#xD;&#xA;3: U-Shape&#xD;&#xA;4: O-Shape" left="-1712.79224385071" top="513.569161262728" width="325.6" height="145" fontSize="14" InitialTop="590.769161262728" InitialHeight="97.8" TextblockHeight="67.2" backgrouund="#FFC1D676">
      <Models ModelGuid="33ba284a-d44c-483c-8356-6b522a1aba3b" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="88af3ec1-c465-4df4-a65f-6b6414c7b4b8" annotationText="SHELL POSITION" left="-1715.24226564225" top="283.319062169192" width="325.76810993903" height="154.79419144045" fontSize="14" InitialTop="313.319062169192" InitialHeight="154.79419144045" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="3583cc96-63cb-47e9-8334-6a5a81c8d474" />
      <Models ModelGuid="e762aceb-495d-4afd-b038-88c38e57ac1e" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="f65d4791-4b1a-46ab-b772-3be292386b27" annotationText="CONVERSION OF GEOMETRY (3D-POINTS) TO 3D-POINT OBJECTS READ BY SHELLTOOL DLL" left="925.474654807777" top="-72.1662872076158" width="576.912763217963" height="447.061629600424" fontSize="14" InitialTop="-42.1662872076158" InitialHeight="447.061629600424" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="7c1d3e37-8e2e-4173-8e7c-2f6d41cbc187" />
      <Models ModelGuid="957ee957-02eb-437e-94bb-ad1f1b8ec4dc" />
      <Models ModelGuid="6b1a63a0-ce1e-4a7d-9aa5-17475b23f013" />
      <Models ModelGuid="908eab93-7b0b-4fb4-a266-1ef6361fab86" />
      <Models ModelGuid="273371d7-c8f0-4c99-a493-aeb02525a261" />
      <Models ModelGuid="0ed1a482-e7d3-4416-af78-57baa533c095" />
      <Models ModelGuid="1f3acc4c-0721-407c-a0c3-874b6c60e172" />
      <Models ModelGuid="6a08f236-352e-4551-8949-99ed3c2653d0" />
      <Models ModelGuid="22e5933c-134c-4f0d-9c91-55bf2b2af594" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="f6f268e4-8438-432b-b645-d9a87ef16809" annotationText="GET STL FROM TRIANGLES" left="1554.1203853175" top="38.5326410335754" width="282.74083898225" height="173.8" fontSize="14" InitialTop="68.5326410335754" InitialHeight="173.8" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="3aceb43e-2fdb-4a99-8fd2-ba59ae7f740e" />
      <Models ModelGuid="9c2eca6c-5ab7-4d16-a6f3-27271bae103b" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="c9f26045-90e0-4cf3-bdc0-a731070c139a" annotationText="GET TRIANGULAR FACETS FROM THE SURFACES COMPOSING THE SHELL&#xD;&#xA;EVERY FACET IS REPRESENTED BY THE 3 POINTS FORMING THE TRIANGLE" left="132.099781613745" top="16.4856744965696" width="598.471929034194" height="304.465426299581" fontSize="14" InitialTop="60.0856744965696" InitialHeight="290.865426299581" TextblockHeight="33.6" backgrouund="#FFC1D676">
      <Models ModelGuid="cfd4dda4-31a0-4fbc-abe6-b065c28ff3e2" />
      <Models ModelGuid="b175dc4e-4bd1-4969-82dc-a87f0ce60a07" />
      <Models ModelGuid="d6bb8c30-5722-4a06-9345-f6f3edb2ce4f" />
      <Models ModelGuid="67bc0b7a-d173-4f1d-a870-b173ec8f567d" />
      <Models ModelGuid="1510dc9f-e608-406a-8a55-b3127bcc3f1e" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="85ffc220-29f0-4e88-a086-e3c2d84f6bc6" annotationText="GET GRIDS IN ASCII FORMAT" left="2244.84814799337" top="198.983503620032" width="865.35266846211" height="238.306781061488" fontSize="14" InitialTop="228.983503620032" InitialHeight="238.306781061488" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="98753061-6787-4b1e-8374-219b94411d65" />
      <Models ModelGuid="00ed6579-98e8-4588-9b15-3af8fa2918af" />
      <Models ModelGuid="d9387d71-ab8e-45e1-9e1c-13503f78d2fa" />
      <Models ModelGuid="6317b1a3-ff61-4820-bea8-6e06fc3851eb" />
      <Models ModelGuid="e811a796-6e5b-475b-91ee-58e860f7a9d9" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="08b6bccd-7991-490f-ba25-a117fef05aca" annotationText="GET FLOOR OUTLINES IN ASCII FORMAT" left="2243.12337889323" top="-28.186021901276" width="626.45177587837" height="213.834084065898" fontSize="14" InitialTop="1.81397809872396" InitialHeight="213.834084065898" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="73f75a9c-506b-4224-8754-b253c5a69949" />
      <Models ModelGuid="3becfda5-9309-446f-9c2d-977f26d6a0a1" />
      <Models ModelGuid="efda527c-0e38-4458-824c-5be24afed77f" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="6f2afaa6-2531-4f5a-9fee-4064dc3547f9" annotationText="GET STL TO ASCII FORMAT" left="2243.28059831862" top="-178.227234400419" width="138.4" height="136.2" fontSize="14" InitialTop="-134.627234400419" InitialHeight="122.6" TextblockHeight="33.6" backgrouund="#FFC1D676">
      <Models ModelGuid="bf84697c-4f18-4a9a-90b4-a0721483a1a1" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="96b46625-0b16-4c78-97c7-a0ef83fa70f8" annotationText="CREATE OUTPUT MESH" left="3002.63504138166" top="-250.121882703415" width="438.51554654152" height="344.811097046812" fontSize="14" InitialTop="-220.121882703415" InitialHeight="344.811097046812" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="d7070713-9c39-4b1d-bc11-00ad7eac31eb" />
      <Models ModelGuid="9328035f-8cc3-4cab-8818-339433070430" />
      <Models ModelGuid="22abe38f-688a-4439-84dd-6b6b50f27647" />
      <Models ModelGuid="8f34147b-e347-4de4-b8a8-c7c6a503c8b5" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="54a8b4fc-cbfb-4716-8e28-2e14dbf3415f" annotationText="ADD MESH TO A DESIGN OBJECT" left="3482.38006128407" top="-246.679433033696" width="263.49103310005" height="180.637990862817" fontSize="14" InitialTop="-216.679433033696" InitialHeight="180.637990862817" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="79136c5b-0a99-435c-ac4e-f04d855a7987" />
      <Models ModelGuid="1b394512-c523-4af3-b703-92a6fbfc0457" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="b305d60f-9eef-4596-8793-ca15ac90ab36" annotationText="VISUALIZE FLOOR OUTLINES - DEBUGGING" left="-480.266179412833" top="1011.40810371631" width="310.794463494965" height="176.39723174748" fontSize="14" InitialTop="1041.40810371631" InitialHeight="173.638399350176" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="32349991-1a1b-4864-99ff-804d2b296b23" />
      <Models ModelGuid="f8508df9-53bf-47a3-b72e-fd51f861f1a2" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="-82.6695958965554" eyeY="229.501792380396" eyeZ="-99.9521364556307" lookX="73.6835078118259" lookY="-103.293682132178" lookZ="128.658655476523" />
  </Cameras>
</Workspace>