{
  "$type": "System.Dynamic.ExpandoObject, System.Core",
  "guid": "00000000-0000-0000-0000-000000000000",
  "name": "Home",
  "nodes": [
    {
      "$type": "System.Dynamic.ExpandoObject, System.Core",
      "_id": "50dcecd5-1850-4824-b8f0-563fcc1cd004",
      "name": "Python Script",
      "position": [
        301.83246073298403,
        201.811518324607
      ],
      "typeName": "Python Script",
      "creationName": "Python Script",
      "displayName": "Akaba.Result",
      "selected": false,
      "visible": true,
      "ignoreDefaults": [],
      "replication": "applyDisabled",
      "extra": {
        "$type": "<>f__AnonymousType7`2[[System.String[], mscorlib],[System.String, mscorlib]], Reach",
        "varInputs": [],
        "script": "import clr\nclr.AddReference('ProtoGeometry')\nfrom Autodesk.DesignScript.Geometry import *\ndataEnteringNode = IN\nOUT = 3"
      }
    }
  ],
  "connections": [],
  "isCustomNode": false,
  "customNodeDescription": "",
  "customNodeCategory": "",
  "offset": [
    0.0,
    0.0
  ],
  "isCustomizer": true
}
